//MIDI CC control numbers
//These broadly follow standard CC assignments
#define   CCmodwheel  1 //pitch LFO amount - less from mod wheel
#define   CCLfoDepth  3 //pitch LFO amount - panel control
#define   CCglideTime 5
#define   CCglideSW 6
#define   CCvolumeControl 7
#define   CCfilterA 8
#define   CCfilterB 9
#define   CCosc1fmWaveMod 10
#define   CCfilterC 11
#define   CCosc1WaveMod 12
#define   CCosc2WaveMod 13
#define   CCosc2fmWaveMod 14
#define   CCosc1fmDepth 15
#define   CCosc1Tune 16
#define   CCosc2Tune 17
#define   CCosc1WaveSelect 18
#define   CCosc2WaveSelect 19
#define   CCosc2fmDepth 20

#define   CCfilterLFO 22
#define   CCnoiseLevel  23
#define   CCfilterPoleSW 24//Off/On
#define   CCKeyTrack  30//Off/On
#define   CCFilterLoop 31
#define   CCAmpLoop 32
#define   CCAmpGatedSW 33
#define   CCeffectBankSW 34
#define   CCeffectNumSW 35
#define   CCosc1Level 37
#define   CCfilterType 39
#define   CCosc2Level 42
#define   CCfilterRelease  44
#define   CCfilterAttack 45
#define   CCfilterSustain  46
#define   CCfilterDecay  47
#define   CCfilterLevel  48
#define   CCfilterEGinv  50
#define   CCfilterEGlevel  53
#define   CCfilterVelSW  54
#define   CCampVelSW 55
#define   CCampRelease  57
#define   CCampAttack 58
#define   CCampSustain  59
#define   CCampDecay  60
#define   CCkeyboardMode  61
#define   CCNotePriority  62
#define   CCmonoMultiSW  63
#define   CCosc2Bank 65
#define   CCPitchBend 66
#define   CCosc2BankB  68
#define   CCosc1OctB 71
#define   CCfilterCutoff  74
#define   CClfoAlt  76
#define   CCLFORate 77
#define   CClfoMult 78
#define   CCosc1osc2fmDepth 79
#define   CCosc1Oct 80
#define   CCosc2Oct  81
#define   CCosc2OctB  82
#define   CCeffect1 83
#define   CCeffect2  84
#define   CCeffect3  85
#define   CCeffectMix  86
#define   CCamDepth  87
#define   CCenvLinLogSW  88
#define   CCLFOWaveform  91
#define   CClfoDelay  92
#define   CCLFOWaveformButton  93
#define   CCfilterRes  94
#define   CCosc1Bank  102
#define   CCosc1BankB  103
#define   CCallnotesoff 123//Panic button